# Generated by Django 6.0.7 on 2026-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='LTE есть')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
    ]
